import os
import shutil
import asyncio
from pathlib import Path
from fastapi import FastAPI, UploadFile, File, BackgroundTasks
from fastapi.responses import JSONResponse
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles

from config.settings import TASKS_DIR
from utils.task import TaskManager
from video.processor import extract_audio
from asr.recognizer import ASRRecognizer
from llm.generator import ArticleGenerator
from screenshot.extractor import ScreenshotExtractor
from utils.html_builder import build_html_article

# Initialize NLP models
asr_model = ASRRecognizer()
llm_model = ArticleGenerator()
screenshot_tool = ScreenshotExtractor()

app = FastAPI(title="Clip2Post V2 API")

# Allow CORS for React dev server
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"], # For development
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Mount tasks directory for static file access (images, html)
app.mount("/tasks", StaticFiles(directory=str(TASKS_DIR)), name="tasks")

def process_video_pipeline(task_id: str, video_path: Path):
    """Background task to process the video step-by-step."""
    task_manager = TaskManager(task_id=task_id)
    
    try:
        # Step 2: Audio Extraction
        task_manager.update_status(0.2, "正在提取音频...", "processing")
        audio_path = task_manager.get_dir("audio") / "audio.wav"
        extract_audio(video_path, audio_path)
        
        # Step 3: ASR (Subtitle Generation)
        task_manager.update_status(0.4, "正在识别字幕...", "processing")
        subtitle_path = task_manager.get_dir("subtitle") / "subtitle.txt"
        asr_model.recognize(audio_path, subtitle_path)
        
        # Step 4: LLM Generation
        task_manager.update_status(0.6, "AI 正在生成文章与图片时间点...", "processing")
        article_path = task_manager.get_dir("ai") / "article.md"
        image_json_path = task_manager.get_dir("ai") / "image.json"
        llm_model.generate(subtitle_path, article_path, image_json_path)
        
        # Step 5: Screen Capture
        task_manager.update_status(0.8, "正在自动截图...", "processing")
        images_dir = task_manager.get_dir("images")
        images_data = screenshot_tool.extract(video_path, image_json_path, images_dir)
        
        # Step 6: HTML Generation
        task_manager.update_status(0.9, "正在排版最终文章...", "processing")
        html_path = task_manager.get_dir("article") / "article.html"
        build_html_article(article_path, images_data, html_path)
        
        task_manager.update_status(1.0, "处理完成！", "completed")

    except Exception as e:
        import traceback
        task_manager.update_status(1.0, f"处理失败: {str(e)}", "error")
        print(traceback.format_exc())

@app.post("/api/upload")
async def upload_video(background_tasks: BackgroundTasks, file: UploadFile = File(...)):
    """Upload video file and start background processing."""
    task_manager = TaskManager()
    task_id = task_manager.task_id
    
    # Save uploaded file
    video_dir = task_manager.get_dir("video")
    video_path = video_dir / "source.mp4"
    
    with open(video_path, "wb") as buffer:
        shutil.copyfileobj(file.file, buffer)
        
    task_manager.update_status(0.1, "文件上传成功，初始化处理...", "processing")
    
    # Start background task
    background_tasks.add_task(process_video_pipeline, task_id, video_path)
    
    return {"task_id": task_id, "message": "Task started."}

@app.get("/api/status/{task_id}")
async def get_status(task_id: str):
    """Poll task status."""
    task_manager = TaskManager(task_id=task_id)
    return task_manager.get_status()

@app.get("/api/results/{task_id}")
async def get_results(task_id: str):
    """Retrieve text/markdown and file paths generated by task."""
    task_manager = TaskManager(task_id=task_id)
    status = task_manager.get_status()
    
    if status.get("state") != "completed":
        return JSONResponse(status_code=400, content={"error": "Task not completed yet."})

    # Read subtitles
    subtitle_content = ""
    subtitle_path = task_manager.get_dir("subtitle") / "subtitle.txt"
    if subtitle_path.exists():
        with open(subtitle_path, 'r', encoding='utf-8') as f:
            subtitle_content = f.read()

    # Read markdown
    article_content = ""
    article_path = task_manager.get_dir("ai") / "article.md"
    if article_path.exists():
        with open(article_path, 'r', encoding='utf-8') as f:
            article_content = f.read()

    # Get images (URL structure over static file mount)
    images_dir = task_manager.get_dir("images")
    images_urls = [f"/tasks/{task_id}/images/{img.name}" for img in sorted(images_dir.glob("*.jpg"))] if images_dir.exists() else []

    html_url = f"/tasks/{task_id}/article/article.html"
    
    return {
        "subtitles": subtitle_content,
        "markdown": article_content,
        "images": images_urls,
        "html_url": html_url
    }

if __name__ == "__main__":
    import uvicorn
    uvicorn.run("main:app", host="0.0.0.0", port=8000, reload=True)
